(define (make-account balance password)
  (let ((alarm-limit 0))
    (define (call-the-cops)
      (display "You have tried the max time for password"))
    (define (withdraw amount)
      (if (>= balance amount)
	  (begin (set! balance (- balance amount))
		 balance)
	  "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch passwd m)
      (if (eq? passwd password)
	  (set! alarm-limit 0
	   (cond ((eq? m 'withdraw) withdraw)
		 ((eq? m 'deposit) deposit)
		 (else (error "Unknow method: MAKE-ACCOUNT" m))))
	  (set! alarm-limit (+ alarm-limit 1)
	   (if (> alarm-limit 7)
	       (call-the-cops)
	       (error "Incorrect password")))))
    dispatch))
