(define (entry tree)(car tree))
(define (left-branch tree) (cadr tree))
(define (right-branch tree) (caddr tree))
(define (lookup given-key set-of-records)
  (cond ((null? set-of-records) #f)
	((equal? given-key (entry set-of-records)) #t)
	((> given-key (entry set-of-records))
	 (lookup given-key (right-branch set-of-records)))
	(else (lookup given-key (left-branch set-of-records)))))
